spring:
  devtools:
    livereload:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb;
    username: sa
    password:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
  h2:
    console:
      enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_APPLICATION_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true